name: flutter_soloud
description: >-
  A low-level audio plugin for Flutter,
  mainly meant for games and immersive apps.
  Based on the SoLoud (C++) audio engine.
version: 2.0.2
issue_tracker: https://github.com/alnitak/flutter_soloud/issues
homepage: https://github.com/alnitak/flutter_soloud
maintainer: Marco Bavagnoli (@lildeimos)
platforms:
  android:
  ios:
  linux:
  macos:
  windows:
topics:
  - audio
  - player
  - games

screenshots:
  - description: "audio FFT data"
    path: img/screenshot.png

environment:
  sdk: '>=3.3.0 <4.0.0'
  flutter: '>=3.3.0'

dependencies:
  ffi: ^2.0.2
  flutter:
    sdk: flutter
  http: ^1.1.0
  logging: ^1.0.0
  meta: ^1.0.0
  path: ^1.8.1
  path_provider: ^2.0.15
  plugin_platform_interface: ^2.1.5

dev_dependencies:
  ffigen: ^9.0.1
  flutter_test:
    sdk: flutter
  test: ^1.24.9
  very_good_analysis: ^5.1.0

flutter:
  plugin:
    platforms:
      android:
        ffiPlugin: true
      ios:
        ffiPlugin: true
      linux:
        ffiPlugin: true
      macos:
        ffiPlugin: true
      windows:
        ffiPlugin: true
